Awards endpoint
KamranDjourshari24/Group19-Project-Base pull request #18
Opened 2021-11-06 21:16 UTC by ngaffney22

2021-11-06 22:27 UTC, KamranDjourshari24 requested changes
Looks good! The only changes needed are adding films to the rewards SQL query. Also, I think we need to change the HTTP methods to conduct the right actions.

2021-11-07 21:22 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +      const createStatement = `INSERT INTO awards (award_id, award_title) VALUES (${currentID}, '${req.body.award_title}', ${awardId})`;
Statement has an extra value being inserted that isn't needed. It should be `INSERT INTO awards (award_id, award_title) VALUES (${currentID}, '${req.body.award_title}')`

2021-11-07 21:31 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +      const awardId = awardName.map((movAward) => movAenre.award_id)[0];
Typo here need movAward

2021-11-07 21:31 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +        SET award_title = '${req.body.award_title}', award_id = ${awardId}
don't need award_id here since we are using it in our where clause

2021-11-07 21:51 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +      const awardID = awardTitle.map((awardName) => awardName.award_id)[0];
Don't need this line since we aren't using awardName anywhere here

2021-11-07 21:51 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +      const awardTitle = getIDByValue(award_title, req.body.award_title);
This should be a variable named awardName (instead of awardTitle) since you used it as awardName right below it

2021-11-07 21:51 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +        WHERE award_id = '${awardId}' `;
your `awardId` should be `awardID` like the variable set on the line before

2021-11-07 21:51 UTC, KamranDjourshari24 commented on routes/nickroutes.js
> +      const createStatement = `INSERT INTO awards (award_id, award_title) VALUES (${currentID})`;
missing in the award title here. It should be:

`INSERT INTO awards (award_id, award_title) VALUES (${currentID}, "${req.body.award_title}")`

2021-11-07 21:55 UTC, KamranDjourshari24 commented on controllers/awardsController.js
> +    USING(film_id)`;
Change this USING(film_id) to a ON statement:
`ON al.film_id = f1.film_id`

Needed since the awards_linking has the film_id not the awards table

2021-11-07 23:38 UTC, KamranDjourshari24 approved these changes
Nice!

2021-11-09 18:26 UTC, Joshua-Cyriac reviewed
Looks Good!

2021-11-09 18:34 UTC, merged