Nick carousel top100
KamranDjourshari24/Group19-Project-Base pull request #30
Opened 2021-11-22 00:42 UTC by ngaffney22

I still have to fix the JS with accessing the API I will have to meet with a TA because I don't understand it enough to iterate over the array of movie titles I created. For looks I temporarily put in images though so we still have a working image carousel. I just don't have any more time for this assignment today. they might allow a late submission tomorrow though so I can re-submit it.

2021-11-22 04:15 UTC, KamranDjourshari24 approved these changes
Looks good

2021-11-22 20:46 UTC, lavendermistyco commented
Hey, I can't pull up your branch on my computer.

2021-11-23 15:12 UTC, lavendermistyco requested changes

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  async function getImage() {
getImage(imageList)

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +      const frontUrl = 'https://api.themoviedb.org/3/search/movie?api_key=ee671a8f0facbafb2b7da0decd7157db&query='
const imageList = [ ];

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +    }
return imageList;

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  getImage()
const imageSlides = getImage(imageList);

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  img1.src = imageList[0];
img1.src = imageSlides[0] ;

2021-11-23 15:12 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  getImage()
This explains why it was null because it wasn't  returning any arraylist. Make sense? @ngaffney22

2021-11-23 15:18 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +      console.log(imageRequest);
Instantiate a list here in this methos instead, so 
Const imageList = [ ];

2021-11-23 15:22 UTC, lavendermistyco requested changes

2021-11-23 15:22 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  async function getImage() {
getImage(movieList);

2021-11-23 15:24 UTC, lavendermistyco requested changes

2021-11-23 15:24 UTC, lavendermistyco commented on client/top-100/top-100Script.js
> +  const imageList = [];
Place this line inside your async function

2021-11-23 16:35 UTC, merged